# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUzuhyGg_IYWJ0iXUSo-5C6gZf7iwJlp
"""



print("Hello")